"""empty message

Revision ID: 0fb189c709f3
Revises: 
Create Date: 2019-02-16 11:12:15.654563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb189c709f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbfsync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbfsyncid', sa.String(length=10), nullable=True,default='dbfsyncid'),
    sa.Column('dbfsynccontent', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbfsync')
    # ### end Alembic commands ###
